export default {
  teamName: "",
  manager: { firstName: "", lastName: "" },
  bench: [
    { firstName: "", lastName: "", isGk: true },
    { firstName: "", lastName: "", isGk: false },
    { firstName: "", lastName: "", isGk: false },
    { firstName: "", lastName: "", isGk: false },
    { firstName: "", lastName: "", isGk: false },
    { firstName: "", lastName: "", isGk: false },
    { firstName: "", lastName: "", isGk: false },
  ],
  players: [
    {
      position: "GK",
      firstName: "",
      lastName: "",
      number: 1,
      isCaptain: true,
      country: { code: "gbr" },
    },
    {
      position: "CB",
      firstName: "",
      lastName: "",
      number: 4,
      isCaptain: false,
      country: { code: "gbr" },
    },
    {
      position: "CB",
      firstName: "",
      lastName: "",
      number: 5,
      isCaptain: false,
      country: { code: "gbr" },
    },
    {
      position: "RB",
      firstName: "",
      lastName: "",
      number: 2,
      isCaptain: false,
      country: { code: "gbr" },
    },
    {
      position: "LB",
      firstName: "",
      lastName: "",
      number: 3,
      isCaptain: false,
      country: { code: "gbr" },
    },
    {
      position: "CM",
      firstName: "",
      lastName: "",
      number: 6,
      isCaptain: false,
      country: { code: "gbr" },
    },
    {
      position: "RCM",
      firstName: "",
      lastName: "",
      number: 8,
      isCaptain: false,
      country: { code: "gbr" },
    },
    {
      position: "LCM",
      firstName: "",
      lastName: "",
      number: 10,
      isCaptain: false,
      country: { code: "gbr" },
    },
    {
      position: "RF",
      firstName: "",
      lastName: "",
      number: 11,
      isCaptain: false,
      country: { code: "gbr" },
    },
    {
      position: "LF",
      firstName: "",
      lastName: "",
      number: 7,
      isCaptain: false,
      country: { code: "gbr" },
    },
    {
      position: "CF",
      firstName: "",
      lastName: "",
      number: 9,
      isCaptain: false,
      country: { code: "gbr" },
    },
  ],

  formation: {
    gk: {
      position: "GK",
      firstName: "",
      lastName: "",
      isCaptain: true,
    },
    def: [
      {
        position: "CB",
        firstName: "",
        lastName: "",
        isCaptain: false,
      },
      {
        position: "CB",
        firstName: "",
        lastName: "",
        isCaptain: false,
      },
      {
        position: "RB",
        firstName: "",
        lastName: "",
        isCaptain: false,
      },
      {
        position: "LB",
        firstName: "",
        lastName: "",
        isCaptain: false,
      },
    ],
    mid: [
      {
        position: "CM",
        firstName: "",
        lastName: "",
        isCaptain: false,
      },
      {
        position: "RCM",
        firstName: "",
        lastName: "",
        isCaptain: false,
      },
      {
        position: "LCM",
        firstName: "",
        lastName: "",
        isCaptain: false,
      },
    ],
    att: [
      {
        position: "RF",
        firstName: "",
        lastName: "",
        isCaptain: false,
      },
      {
        position: "LF",
        firstName: "",
        lastName: "",
        isCaptain: false,
      },
      {
        position: "CF",
        firstName: "",
        lastName: "",
        isCaptain: false,
      },
    ],
  },
  countries: new Map(),
};
